# fly.toml
app = "auth-sqlite"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "3000"

[[services]]
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = "80"

  [[services.ports]]
  handlers = ["tls", "http"]
  port = "443"

[mounts]
  source="data_volume"
  destination="/data"